// EXER21_react_traging/react_scaffold/02_src_hello_react/src/App.js
import React,{Component} from 'react';
import Hello from './Components/Hello'
import Welcome from './Components/Welcome'


export default class App extends Component{
    render(){
        return (
            <div>
                <Hello></Hello>
                <Welcome></Welcome>
            </div>
        )
    }
}

// EXER18_vue2/vue_baisc/19_单文件组件/App.vue
<template>
  <div>
    <Student></Student>
    <School></School>
  </div>
</template>

<script>
    import Student from './School.vue'
    import School from './Student.vue'
    export default {
        components:{
            Student,
            School
        },
        template:`<App></App>`,
        name:'App'
    }
</script>
